<a href="https://colab.research.google.com/github/SuryARavichan/NUMPY/blob/main/NUMERICAL_PYTHON.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
type(my_list)

list

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
myarr = np.array(my_list)

In [6]:
myarr

array([1, 2, 3])

In [7]:
type(myarr)

numpy.ndarray

In [8]:
mymatrix = [[2,4,6,8,10],[1,3,7,9,10],[12,48,79,20,56]]

In [9]:
np.array(mymatrix)

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  7,  9, 10],
       [12, 48, 79, 20, 56]])

In [10]:
type(mymatrix)

list

In [11]:
np.arange(5,20,3)

array([ 5,  8, 11, 14, 17])

In [12]:
np.zeros(17)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones(23)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [16]:
np.zeros((8,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
np.zeros((4,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [18]:
np.ones((6,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.linspace(5,23,4)

array([ 5., 11., 17., 23.])

In [20]:
np.linspace(5,89,25)

array([ 5. ,  8.5, 12. , 15.5, 19. , 22.5, 26. , 29.5, 33. , 36.5, 40. ,
       43.5, 47. , 50.5, 54. , 57.5, 61. , 64.5, 68. , 71.5, 75. , 78.5,
       82. , 85.5, 89. ])

In [21]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [22]:
np.eye(35)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [23]:
np.random.randint(3,56,12)

array([11, 21, 37, 31, 41, 49, 40, 10, 39, 47, 40, 38])

In [26]:
np.random.randint(15,18889,265)

array([18854,  1076,  9360,  7965,  7815,  3057, 10734,  5240, 17780,
       13574, 14504,  3912, 18236, 16827, 13038, 16033,  4122, 18246,
        4027,  5447,  9736,  4705,   373, 11947,    44, 14602,  6353,
        5660, 12575,  7296,  4217,  9873, 12553, 11090,  6903,  2932,
       12730,  9475,  2137, 18215, 11096, 10860, 12491,  5686, 11099,
        8105,  8005,  8722,  4773,  7467,  4709,  7781,  9457, 12822,
       12354,  9607,  1147,  4208, 12248, 17685,  3522,  3067, 10940,
        4231,  3200,  1976, 14509,   798,  7211, 11676, 17871, 18154,
       17748, 10042, 16307,  7014,  2722, 18545, 14374,  1609, 14675,
       12086,  9140, 11160,  8794,  8960, 18669, 13185,  2347,  1669,
       17079, 17293, 15600,  9352, 11653,   824,  9758,  3388,  9335,
       10839, 18391,  8207,  4825, 16560,  3763, 18793,  4638, 17454,
       18733,  1453,  6335, 10539, 17794, 16890,  7348,  6381, 13868,
        9801,  9935,  5380, 13605,  4485,  8826,  6156, 17660, 17522,
         438, 10331,

In [31]:
np.random.rand(8,5)

array([[0.79518684, 0.57913229, 0.78330271, 0.51255576, 0.70782101],
       [0.87664972, 0.55827771, 0.05937113, 0.36687797, 0.77830171],
       [0.34398798, 0.11613255, 0.51847188, 0.28819766, 0.23266854],
       [0.09274854, 0.76470224, 0.98981683, 0.14315136, 0.30208624],
       [0.58488389, 0.1378382 , 0.20912025, 0.5248327 , 0.41138592],
       [0.76285253, 0.5304984 , 0.55192038, 0.09341302, 0.75928853],
       [0.49497042, 0.93591827, 0.48818604, 0.91630114, 0.23106631],
       [0.64801612, 0.07473049, 0.56927165, 0.40906255, 0.77316415]])

In [32]:
np.random.randn(23)

array([ 0.25624322,  1.69658699, -0.1212456 ,  0.82613347, -0.12172179,
        0.37152676,  1.67802236, -1.25634506, -0.87940116, -0.23417345,
        0.70743452, -0.99894209,  0.34218126,  0.76568214, -0.67282305,
       -1.86767722, -0.67025519, -0.07481973,  0.34799735, -0.41442477,
        1.37111051, -1.51328319,  1.64645208])

In [33]:
np.random.randn(5,4)

array([[-0.5395931 ,  0.89177768,  0.36943246,  2.20175786],
       [-0.70597659,  1.22134631, -0.83035052,  0.50521   ],
       [ 0.08573733,  2.75105468, -1.69169742, -1.35090747],
       [ 1.05929942, -0.09271515,  0.28686318, -0.3808485 ],
       [ 1.49320887,  1.03722338,  0.62491674, -0.1079687 ]])

In [34]:
np.random.randint(5,150,(8,3))

array([[ 70,  91,  16],
       [ 23, 138,  23],
       [ 15, 125,  28],
       [140,  94,  32],
       [ 71,  11, 144],
       [118, 100,  83],
       [  8,  46,  67],
       [104,  73,  38]])

In [35]:
np.random.randint(0,100,15)

array([65, 32, 94, 92, 67, 24, 78, 82, 45, 95, 86, 36,  2, 59, 62])

In [36]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [37]:
np.random.seed(65)
np.random.rand(5)

array([0.21864505, 0.03140272, 0.28712528, 0.17264466, 0.30337638])

In [38]:
arr = np.arange(0,25)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
surya = np.random.randint(0,123,18)

In [44]:
max(surya)

101

In [45]:
min(surya)

3

In [47]:
surya.argmax()

14

In [48]:
surya.argmin()

7

In [49]:
surya.dtype

dtype('int64')

In [50]:
surya.shape

(18,)

In [54]:
arr = np.arange(0,11)

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr[6]

6

In [57]:
arr[2:5]

array([2, 3, 4])

In [58]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [59]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [60]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [61]:
arr[0:5] = 100

In [62]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [64]:
arr1 = np.arange(0,11)

In [66]:
slice_of_arr1 = arr[0:7]

In [67]:
slice_of_arr1

array([100, 100, 100, 100, 100,   5,   6])

In [68]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [69]:
slice_of_arr1[:] = 78

In [70]:
slice_of_arr1

array([78, 78, 78, 78, 78, 78, 78])

In [72]:
arr_2d = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [74]:
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [76]:
arr_2d.shape


(3, 3)

In [77]:
arr_2d[2]

array([70, 80, 90])

In [78]:
arr_2d[1][1]

50

In [80]:
arr_2d[2][1]

80

In [81]:
arr_2d[:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [82]:
arr_2d[1,2]

60

In [83]:
arr_2d[:2,1:]

array([[20, 30],
       [50, 60]])

In [85]:
arr = np.arange(1,11)

In [87]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr > 8

array([False, False, False, False, False, False, False, False,  True,
        True])

In [89]:
bool_arr = arr > 5

In [91]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [92]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [96]:
arr = np.arange(0,10)

In [97]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
arr + 8

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [99]:
arr - 15

array([-15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6])

In [100]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
arr * 2656565

array([       0,  2656565,  5313130,  7969695, 10626260, 13282825,
       15939390, 18595955, 21252520, 23909085])

In [102]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [104]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [106]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [107]:
arr / arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [109]:
arr *  arr + 150

array([150, 151, 154, 159, 166, 175, 186, 199, 214, 231])

In [110]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [111]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [112]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [113]:
np.cosh(arr)

array([1.00000000e+00, 1.54308063e+00, 3.76219569e+00, 1.00676620e+01,
       2.73082328e+01, 7.42099485e+01, 2.01715636e+02, 5.48317035e+02,
       1.49047916e+03, 4.05154203e+03])

In [114]:
np.sinc(arr)

array([ 1.00000000e+00,  3.89817183e-17, -3.89817183e-17,  3.89817183e-17,
       -3.89817183e-17,  3.89817183e-17, -3.89817183e-17,  3.89817183e-17,
       -3.89817183e-17,  3.89817183e-17])

In [115]:
arr.sum()

45

In [116]:
arr.mean()

4.5

In [117]:
arr.mean()

4.5

In [118]:
arr.std()

2.8722813232690143

In [119]:
arr.max()

9

In [120]:
arr.min()

0

In [121]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [123]:
arr_3d = np.arange(0,25).reshape(5,5)

In [124]:
arr_3d.sum()

300

In [125]:
arr_3d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [126]:
arr_3d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [127]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [128]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [129]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [130]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [131]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [132]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [133]:
np.random.rand(1)

array([0.91663181])

In [134]:
np.random.randn(25)

array([ 0.05513006,  0.87392396,  2.04422225, -0.24237061,  0.26355169,
       -1.55965126, -0.21145083,  0.23927092,  0.09105838,  0.56207583,
        0.94441992,  1.33708981, -1.44076818, -1.16033082, -0.36190042,
        0.62632382, -0.44429199,  0.17076588, -0.72719763,  0.67971892,
       -1.47450754, -0.2407805 , -0.33213663, -0.17548503,  1.37306053])

In [136]:
arr = np.arange(1,101) / 100

In [138]:
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [139]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [140]:
mat = np.arange(1,26).reshape(5,5)

In [141]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [142]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [143]:
mat[3:4]

array([[16, 17, 18, 19, 20]])

In [144]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [145]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [146]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [148]:
mat.sum()

325

In [149]:
mat.std()

7.211102550927978

In [150]:
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])