<a href="https://colab.research.google.com/github/SuryARavichan/NUMPY/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
myarray = np.array(mylist)

In [6]:
myarray

array([1, 2, 3])

In [7]:
type(myarray)

numpy.ndarray

In [8]:
mymatrix = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(mymatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
type(mymatrix)

list

In [13]:
np.arange(0,150,28)


array([  0,  28,  56,  84, 112, 140])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros(16)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((7,7))


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [18]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.ones((9,9))


array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
np.linspace(5,30)


array([ 5.        ,  5.51020408,  6.02040816,  6.53061224,  7.04081633,
        7.55102041,  8.06122449,  8.57142857,  9.08163265,  9.59183673,
       10.10204082, 10.6122449 , 11.12244898, 11.63265306, 12.14285714,
       12.65306122, 13.16326531, 13.67346939, 14.18367347, 14.69387755,
       15.20408163, 15.71428571, 16.2244898 , 16.73469388, 17.24489796,
       17.75510204, 18.26530612, 18.7755102 , 19.28571429, 19.79591837,
       20.30612245, 20.81632653, 21.32653061, 21.83673469, 22.34693878,
       22.85714286, 23.36734694, 23.87755102, 24.3877551 , 24.89795918,
       25.40816327, 25.91836735, 26.42857143, 26.93877551, 27.44897959,
       27.95918367, 28.46938776, 28.97959184, 29.48979592, 30.        ])

In [22]:
np.linspace(67,120,13)

array([ 67.        ,  71.41666667,  75.83333333,  80.25      ,
        84.66666667,  89.08333333,  93.5       ,  97.91666667,
       102.33333333, 106.75      , 111.16666667, 115.58333333,
       120.        ])

In [23]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [24]:
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.eye(17)



array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0

In [30]:
np.random.rand(5,15)

array([[0.52466924, 0.41722122, 0.13526375, 0.07518195, 0.47782189,
        0.22755409, 0.50427746, 0.03361943, 0.03227567, 0.04963565,
        0.32349295, 0.29876914, 0.12459421, 0.24730714, 0.44485557],
       [0.28761222, 0.77249989, 0.5426151 , 0.98129918, 0.60604538,
        0.17341533, 0.4763732 , 0.12249922, 0.55549039, 0.95511049,
        0.17588569, 0.09088178, 0.50431245, 0.67169095, 0.75805728],
       [0.8220206 , 0.41652627, 0.22112604, 0.87719074, 0.07551661,
        0.98315842, 0.9155432 , 0.1519615 , 0.80125119, 0.86205026,
        0.8054052 , 0.18256018, 0.90343253, 0.04970712, 0.82365327],
       [0.40539291, 0.62067095, 0.075031  , 0.82209864, 0.66986922,
        0.36114726, 0.27651842, 0.9083221 , 0.42700835, 0.74112349,
        0.43955175, 0.43898104, 0.47324916, 0.06852524, 0.96663553],
       [0.12160186, 0.54319767, 0.35630905, 0.24332501, 0.65164628,
        0.52312362, 0.13251749, 0.2272452 , 0.83767426, 0.23337499,
        0.56985345, 0.64465258, 0.46810285, 

In [32]:
np.random.randn(5,76)

array([[-2.37650157e-01,  1.06962280e+00,  6.07594449e-01,
         2.38414634e-01, -9.02450911e-01,  1.82360985e-01,
        -1.03582384e+00, -2.14135824e+00, -1.44720900e+00,
         3.16652065e-01,  1.58696526e+00, -1.50707619e+00,
        -4.07032458e-02, -1.49037766e+00,  5.71523882e-01,
         2.50412968e-01,  7.12514941e-01, -5.11986838e-01,
         5.47246596e-01, -1.43947047e-01, -7.61322045e-01,
        -1.34234976e+00,  1.92464695e+00, -9.60887866e-01,
         4.87355032e-01,  1.34368591e+00, -2.13660583e+00,
        -1.92077177e+00, -3.02299601e-01,  1.47152968e+00,
        -1.19275611e+00, -6.68017110e-02,  1.00384959e+00,
        -1.31732451e+00, -1.20151654e-01, -9.68225414e-01,
        -8.83031262e-01,  1.27413499e+00, -3.38609697e-01,
        -1.20149257e+00, -9.83649425e-01, -2.50301657e+00,
        -2.69880879e-01,  1.72936931e+00,  3.88520536e-01,
        -1.15962133e-02,  2.75343977e-01, -5.10519229e-01,
         3.43622186e-02,  6.52879114e-01, -8.22048068e-0

In [33]:
np.random.randn(3,5)


array([[-1.31214044,  0.1463683 ,  1.41283838,  0.60062879,  1.24187167],
       [-0.43341391, -0.92740016, -0.21967831,  0.4947888 , -0.26688999],
       [-0.2425431 , -0.62656434,  0.78428943,  0.9756241 ,  0.2194552 ]])

In [37]:
np.random.randint(4,17878,(3,6))

array([[10178, 13804, 15231, 13028,  7866,  3392],
       [ 3189,  2719,  2326, 11695, 15849, 15195],
       [ 3269,    71,  4004, 15556,  3134, 10780]])

In [40]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [41]:
arr = np.arange(0,25)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
arr.reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
np.random.randint(0,101,12)

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52,  1, 87])

In [47]:
np.random.randint(0,101,12).max()


88

In [48]:
np.random.randint(0,101,12).min()


14

In [49]:
np.random.randint(0,101,12).argmin()


2

In [50]:
np.random.randint(0,101,12).argmax()


7

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [55]:
arr.shape

(25,)

In [56]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [57]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [58]:
arr = np.arange(0,11,1)

In [59]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr[8]

8

In [61]:
arr[4]

4

In [62]:
arr[1:5]

array([1, 2, 3, 4])

In [63]:
arr[:5]

array([0, 1, 2, 3, 4])

In [64]:
arr[5:7]

array([5, 6])

In [65]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [66]:
arr[0:5] = 100

In [67]:
arr


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [68]:
arr[5:8] = 56

In [69]:
arr

array([100, 100, 100, 100, 100,  56,  56,  56,   8,   9,  10])

In [70]:
arr = np.arange(0,11,1)

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
arr[:] = 78

In [73]:
arr

array([78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78])

In [74]:
arr = np.arange(0,56,8)

In [75]:
arr

array([ 0,  8, 16, 24, 32, 40, 48])

In [77]:
arr_2d = np.array([[5,10,15],[25,30,35],[40,45,55]])

In [78]:
arr_2d


array([[ 5, 10, 15],
       [25, 30, 35],
       [40, 45, 55]])

In [79]:
arr_2d[0]

array([ 5, 10, 15])

In [80]:
arr_2d[2]

array([40, 45, 55])

In [82]:
arr_2d[1,1]


30

In [83]:
arr_2d[0,2]

15

In [84]:
arr_2d[0:2]

array([[ 5, 10, 15],
       [25, 30, 35]])

In [85]:
arr_2d[:2,1:]

array([[10, 15],
       [30, 35]])

In [87]:
arr = np.arange(1,11)

In [88]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [90]:
bool_arr = arr > 4

In [91]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [92]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [93]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [94]:
arr = np.arange(0,10)


In [95]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [97]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [98]:
arr * 1676768

array([       0,  1676768,  3353536,  5030304,  6707072,  8383840,
       10060608, 11737376, 13414144, 15090912])

In [99]:
arr + arr*16

array([  0,  17,  34,  51,  68,  85, 102, 119, 136, 153])

In [100]:
arr - arr


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [101]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
arr / arr


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [103]:
arr / arr * 90

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, 90., 90., 90., 90., 90., 90., 90., 90., 90.])

In [104]:
arr * 156 / arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan, 156., 156., 156., 156., 156., 156., 156., 156., 156.])

In [105]:
1 / arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [106]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [107]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [108]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [109]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [110]:
arr.sum()

45

In [111]:
arr.mean()

4.5

In [112]:
arr.max()

9

In [113]:
arr.min()

0

In [114]:
arr.var()

8.25

In [115]:
arr.std()

2.8722813232690143

In [118]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [119]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
arr.sum()

45

In [122]:
arr.sum(axis=0)

45

In [124]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [125]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [126]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [127]:
np.arange(10,51)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [128]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [129]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [132]:
arr = np.arange(9)

In [133]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [134]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [135]:
np.random.rand(1)

array([0.03131329])

In [136]:
np.random.randn(25)

array([-0.17628566,  1.20089277,  0.69839894, -0.17162884, -0.90718658,
        1.18862573,  0.78553212,  2.65601009,  0.26348604,  1.64177112,
        0.4608163 ,  0.08592347, -1.50995728,  0.72150246, -0.84341992,
       -0.51332541, -0.0435368 , -0.27530091, -1.56306679, -0.79563099,
        0.9305844 ,  0.67776741,  0.69844026,  0.17360206,  0.66228451])

In [138]:
arr = np.arange(1,101) / 100
arr.reshape(10,10)


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [139]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [142]:
mat = np.arange(1,26).reshape(5,5)

In [143]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [144]:
mat[2:1,:]

array([], shape=(0, 5), dtype=int64)

In [145]:
mat[3:4]

array([[16, 17, 18, 19, 20]])

In [146]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [147]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [148]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [151]:
mat.sum()

325

In [152]:
mat.std()

7.211102550927978

In [153]:
mat.mean()

13.0

In [154]:
mat.max()

25

In [155]:
mat.mean()

13.0